sudo: false
language: python

cache:
  directories:
  - "$HOME/.cache/pip"

matrix:
  include:
  - python: 3.8
    env: TOXENV=flake8

  - python: 3.8
    env: TOXENV=py38

install:
  - pip install pip tox codecov twine

deploy:
  provider: pypi
  username: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true

script:
  - tox -e $TOXENV

after_success:
  - codecov
